# Generated by Django 2.2 on 2022-07-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
            ],
        ),
    ]
